/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_juanlopes_ettree_PowMod */

#ifndef _Included_net_juanlopes_ettree_PowMod
#define _Included_net_juanlopes_ettree_PowMod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_juanlopes_ettree_PowMod
 * Method:    boostPowM
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_net_juanlopes_ettree_PowMod_boostPowM
  (JNIEnv *, jclass, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
