/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_juanlopes_ettree_JNIWrapper */

#ifndef _Included_net_juanlopes_ettree_JNIWrapper
#define _Included_net_juanlopes_ettree_JNIWrapper
#ifdef __cplusplus
extern "C" {
#endif
#undef net_juanlopes_ettree_JNIWrapper_P
#define net_juanlopes_ettree_JNIWrapper_P 4611686018427387847LL
/*
 * Class:     net_juanlopes_ettree_JNIWrapper
 * Method:    powm
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_net_juanlopes_ettree_JNIWrapper_powm
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     net_juanlopes_ettree_JNIWrapper
 * Method:    create
 * Signature: (IIJ)J
 */
JNIEXPORT jlong JNICALL Java_net_juanlopes_ettree_JNIWrapper_create
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     net_juanlopes_ettree_JNIWrapper
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_juanlopes_ettree_JNIWrapper_destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_juanlopes_ettree_JNIWrapper
 * Method:    merge
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_net_juanlopes_ettree_JNIWrapper_merge
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     net_juanlopes_ettree_JNIWrapper
 * Method:    clear
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_net_juanlopes_ettree_JNIWrapper_clear
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     net_juanlopes_ettree_JNIWrapper
 * Method:    update
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_net_juanlopes_ettree_JNIWrapper_update
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     net_juanlopes_ettree_JNIWrapper
 * Method:    recover
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_net_juanlopes_ettree_JNIWrapper_recover
  (JNIEnv *, jclass, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
